// src/components/signup/index.vue
<template>
    <card custom-class-name='login-box' shadow>
        <form id='loginForm' onSubmit={this.onSubmit}>
            <card-title custom-class-name='login-title'>
                <card-title-text>Cadastre-se</card-title-text>
            </card-title>
            <card-content>
                <grid>
                    <cell size='12'>
                        <mdl-input v-ref:nome 
                            type="text" 
                            field-label="Nome Completo" 
                            error-message="Campo invalido!" 
                            floating-label required></mdl-input>
                    </cell>
                </grid>
                <grid>
                    <cell size='12'>
                        <mdl-input v-ref:email 
                            type="text" 
                            field-label="E-mail" 
                            error-message="Campo invalido!" 
                            floating-label required></mdl-input>
                    </cell>
                </grid>
                <grid>
                    <cell size='12'>
                        <mdl-input v-ref:senha 
                            type="password" 
                            field-label="Senha" floating-label required></mdl-input>
                    </cell>
                </grid>
            </card-content>
            <card-actions>
               <spacer></spacer>
               <mdl-button raised colored event='onConfirm'>Confirmar</mdl-button>
               &nbsp;
               <link-button flat event='onCancel'>Cancelar</link-button>
            </card-actions>
        </form>
    </card>
</template>

<script>
    import Layout from 'mdl/layout'
    import 'components/login/login.css'
    import store  from 'store'
    import { showLogin, ADD_USER } from 'store/reducers'
    
    export default {
        ready() {
            this.$refs.nome.focus()
        },
        
        events: {
            onCancel() {
                store.dispatch(showLogin())
            },
            
            onConfirm() {
                let model = {
                    nome: this.$refs.nome.value(),
                    email: this.$refs.email.value(),
                    senha: this.$refs.senha.value()
                }
                store.dispatch({ type: ADD_USER, payload: model })
            }
        },
        
        components: {
            spacer: Layout.spacer
        }
    }
</script>

// src/components/signup/index.jsx
import { connect } from 'react-redux'
import { Grid, Cell } from 'mdl/grid'
import { LayoutSpacer } from 'mdl/layout'
import { Card, CardTitle, CardTitleText, CardContent, CardActions } from 'mdl/card'
import { Button, LinkButton } from 'mdl/button'
import Input from 'mdl/input'
import Users from 'api/users'
import { SHOW_LOGIN } from 'store/reducers'

const dispatchToProps = (dispatch) => ({
    doCancel: () => dispatch({ type: SHOW_LOGIN })
})

const Signup = React.createClass({
    onSubmit(ev) {
        ev.preventDefault()
        let model = {
            nome: this.refs.nome.getState().value,
            email: this.refs.email.getState().value,
            senha: this.refs.senha.getState().value
        }
        Users.add(model)
        this.props.notify('Conta criada com sucesso.')
        this.props.doCancel()
    },
    
    onCancel(ev) {
        ev.preventDefault()
        this.props.doCancel()
    },
    
    componentDidMount() {
        this.refs.nome.focus()
    },
    
    render() {
        return (
            <Card customClassName='login-box' shadow={true}>
                <form id='signupForm' onSubmit={this.onSubmit}>
                    <CardTitle customClassName='login-title'>
                        <CardTitleText>
                            Cadastre-se
                        </CardTitleText>
                    </CardTitle>
                    <CardContent>
                        <Grid>
                            <Cell size='12'>
                                <Input ref='nome' type='text' label='Nome Completo' floating-label required />
                            </Cell>
                        </Grid>
                        <Grid>
                            <Cell size='12'>
                                <Input ref='email' type='text' label='E-mail' floating-label required />
                            </Cell>
                        </Grid>
                        <Grid>
                            <Cell size='12'>
                                <Input ref='senha' type='password' label='Senha' floating-label required />
                            </Cell>
                        </Grid>
                    </CardContent>
                    <CardActions>
                        <LayoutSpacer />
                        <Button type='submit' raised colored>Confirmar</Button>
                        <LinkButton flat accent onClick={this.onCancel}>Cancelar</LinkButton>
                    </CardActions>
                </form>
            </Card>
        )
    }
})

export default connect(null, dispatchToProps)(Signup)
