// src/components/login/index.jsx
import { Grid, Cell } from 'mdl/grid'
import { LayoutSpacer } from 'mdl/layout'
import { Card, CardTitle, CardTitleText, CardContent, CardActions } from 'mdl/card'
import { Button, LinkButton } from 'mdl/button'
import Input from 'mdl/input'
import 'components/login/login.css'
import Users from 'api/users'

const Login = React.createClass({
    
    onSubmit(ev) {
        ev.preventDefault()
        let credentails = {
            email: this.refs.email.getState().value,
            senha: this.refs.senha.getState().value
        }
        let usuario = Users.authenticate(credentails)
        if (usuario) {
            this.props.notify(`Ola ${usuario.nome}, seja bem vindo!`)
            console.log('usuario', usuario)
            this.props.onLogin()
        } else {
            this.props.notify('Dados invalidos, tente novamente!')
        }
    },
    
    onSignup(ev) {
        ev.preventDefault()
        this.props.onSignup()
    },
    
    render() {
        return (
            <Card customClassName='login-box' shadow={true}>
                <form id='loginForm' onSubmit={this.onSubmit}>
                    <CardTitle customClassName='login-title'>
                        <CardTitleText>Autentique-se</CardTitleText>
                    </CardTitle>
                    <CardContent>
                        <Grid>
                            <Cell size='12'>
                                <Input ref='email' type='text' label='E-mail' floating-label required />
                            </Cell>
                        </Grid>
                        <Grid>
                            <Cell size='12'>
                                <Input ref='senha' type='password' label='Senha' floating-label required />
                            </Cell>
                        </Grid>
                    </CardContent>
                    <CardActions>
                        <LinkButton flat onClick={this.onSignup}>Cadastrar</LinkButton>
                        <LayoutSpacer />
                        <Button type='submit' ripple colored success>Acessar</Button>
                    </CardActions>
                </form>
            </Card>
        )
    }
})

export default Login

// src/components/login/login.vue
<template>
    <card custom-class-name='login-box' shadow>
        <form id='loginForm' onSubmit={this.onSubmit}>
            <card-title custom-class-name='login-title'>
                <card-title-text>Autentique-se</card-title-text>
            </card-title>
            <card-content>
                <grid>
                    <cell size='12'>
                        <mdl-input v-ref:email 
                            type="text" 
                            field-label="E-mail" 
                            error-message="Campo invalido!" 
                            floating-label required></mdl-input>
                    </cell>
                </grid>
                <grid>
                    <cell size='12'>
                        <mdl-input v-ref:senha 
                            type="password" 
                            field-label="Senha" floating-label required></mdl-input>
                    </cell>
                </grid>
            </card-content>
            <card-actions>
               <link-button flat event='onSignup'>Cadastrar</link-button>
               <spacer></spacer>
               <mdl-button ripple colored success event='onAuthenticate'>Acessar</mdl-button>
            </card-actions>
        </form>
    </card>
</template>

<script>
    import Grid from 'mdl/grid'
    import Layout from 'mdl/layout'
    import 'components/login/login.css'
    
    export default {
        events: {
            onSignup() {
                console.log('-> singup')
            },
            
            onAuthenticate() {
                let credentials = {
                    email: this.$refs.email.value(),
                    senha: this.$refs.senha.value()
                }
                
                // let usuario = Users.authenticate(credentails)
                // if (usuario) {
                //     this.props.notify(`Ola ${usuario.nome}, seja bem vindo!`)
                //     console.log('usuario', usuario)
                //     this.props.onLogin()
                // } else {
                //     this.props.notify('Dados invalidos, tente novamente!')
                // }
                console.log('-> authenticate', credentials)
            }
        },
        
        components: {
            grid: Grid.grid,
            cell: Grid.cell,
            spacer: Layout.spacer
        }
    }
</script>
